<!-- 图片预览 -->
<style media="screen">
    .file-target-preview {
        display: flex;
        flex-direction: row;
        align-items: center;
        flex-wrap: wrap;
        gap: 0.5rem;
        margin-bottom: 0.5rem
    }

    .preview-item {
        display: block;
        position: relative;
        float: left;
        wth: <?= $this->getData('width') ?? 50 ?>px;
        height: <?= $this->getData('height') ?? 50 ?>px;
        border: 1px sol #CCC;
    }

    .close {
        position: absolute;
        right: 0;
        wth: 17px;
        height: 17px;
        z-index: 1;
        text-align: center;
        line-height: 17px;
        background: transparent;
        opacity: 0.5
    }

    .drag-item:hover .close {
        opacity: 1;
        color: red;
    }

    .drag-pic {
        max-wth: 100%;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        margin: auto;
    }
</style>
<div id="{{id}}-preview" class="file-target-preview">
    <foreach name="value_items" key="k">
        <div class="preview-item">
            <img data-src="{{v.path}}" src="{{v.url}}" alt="{{v.pathInfo.name}}"
                 title="{{v.pathInfo.name}}({{v.pathInfo.size}})"
                 class="drag-pic img-responsive"
                 draggable="false"
                 data-file="">
        </div>
    </foreach>
</div>
<!-- 图片放大modal -->
<div class="modal fade bs-example-modal-center bd-example-modal-lg" tabindex="-1" role="dialog"
     aria-labelledby="Elfinder" aria-hden="true" id="{{id}}-zoom-modal">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-fullscreen-md-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <lang>预览</lang>
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" id="{{id}}-zoom-close-modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body" id="{{id}}-zoom-preview-image-body">
                <img src="" alt="" title="">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $('#{{id}}-preview').on('click', 'img', function () {
        let src = '/pub/media/' + $(this).attr('data-src');
        let zoomModal = $('#{{id}}-zoom-modal');
        let zoomPreviewImageBody = $('#{{id}}-zoom-preview-image-body');
        zoomPreviewImageBody.empty()
        zoomPreviewImageBody.append(`<img src="${src}" class="img-flu" alt="">`)
        zoomModal.modal('show')
    })
</script>